// videos
export const FETCH_VIDEOS = 'FETCH_VIDEOS'
export const HIDDEN_VIDEO = 'HIDDEN_VIDEO'
export const FETCH_VIDEOS_BY_USERID = 'FETCH_VIDEOS_BY_USERID'

// user
export const FETCH_SIGNIN_USER = 'FETCH_SIGNIN_USER'
export const SET_SIGNIN_USER = 'SET_SIGNIN_USER'
export const SET_USER_OUT = 'SET_USER_OUT'
export const SET_TOKEN = 'SET_TOKEN'
export const SIGN_BY_USERNAME = 'SIGN_BY_USERNAME'
export const SET_MESSAGE = 'SET_MESSAGE'
export const CLOSE_SIGN_DIALOG = 'CLOSE_SIGN_DIALOG'
export const SHOW_SIGN_DIALOG = 'SHOW_SIGN_DIALOG'
export const FETCH_USER_INFO = 'FETCH_USER_INFO'

// image
export const FETCH_IMAGES = 'FETCH_IMAGES'
